-- =====================================================================
--  Ferie Estive 2026 · Roster collaboratori (allowlist con nomi)
--  Generato dalla lista TS Risorse 2026. Eseguire DOPO schema.sql.
--  140 collaboratori.
-- =====================================================================

create table if not exists public.allowed_emails (
  email    text primary key,
  nome     text,
  cognome  text,
  added_at timestamptz not null default now()
);
alter table public.allowed_emails enable row level security;
drop policy if exists allowlist_admin_all on public.allowed_emails;
create policy allowlist_admin_all on public.allowed_emails
  for all using (public.is_admin()) with check (public.is_admin());
-- lettura del roster consentita agli utenti autenticati (per la dashboard)
drop policy if exists allowlist_read_auth on public.allowed_emails;
create policy allowlist_read_auth on public.allowed_emails
  for select using (auth.role() = 'authenticated');

insert into public.allowed_emails (email, nome, cognome) values
  ('gfalchi@kpmg.it', 'Giacomo', 'Falchi'),
  ('nfuorlo@kpmg.it', 'Nicola', 'Fuorlo'),
  ('pmelzi@kpmg.it', 'Pietro Felice', 'Melzi'),
  ('mzanardini@kpmg.it', 'Mauro', 'Zanardini'),
  ('prolleri@kpmg.it', 'Paolo', 'Rolleri'),
  ('alatella@kpmg.it', 'Alessandro', 'Latella'),
  ('nbottone@kpmg.it', 'Nicola', 'Bottone'),
  ('jritossa@kpmg.it', 'Jacopo', 'Ritossa'),
  ('stefaniastea@kpmg.it', 'Stefania', 'Stea'),
  ('ssimonte@kpmg.it', 'Salvatore', 'Simonte'),
  ('annachiarapino@kpmg.it', 'Annachiara', 'Pino'),
  ('mmladovan@kpmg.it', 'Maria Vittoria', 'Mladovan'),
  ('enricoguerra@kpmg.it', 'Enrico', 'Guerra'),
  ('igrassellini@kpmg.it', 'Irene', 'Grassellini'),
  ('gsconosciuto@kpmg.it', 'Giovanni', 'Sconosciuto'),
  ('ndargenio@kpmg.it', 'Nicolò', 'D''Argenio'),
  ('fnaso@kpmg.it', 'Francesca', 'Naso'),
  ('mabdelazim@kpmg.it', 'Mustafa', 'Abd Elazim'),
  ('nstramare@kpmg.it', 'Nicole', 'Stramare'),
  ('mfranzetti@kpmg.it', 'Marco', 'Franzetti'),
  ('cpiovano@kpmg.it', 'Carlotta', 'Piovano'),
  ('tbattaglia@kpmg.it', 'Tatiana', 'Battaglia'),
  ('acaldarone@kpmg.it', 'Alessandro Aldo', 'Caldarone'),
  ('vgobbo@kpmg.it', 'Veronica', 'Gobbo'),
  ('ecaizzi@kpmg.it', 'Eugenia', 'Caizzi'),
  ('andreacrippa@kpmg.it', 'Andrea', 'Crippa'),
  ('jawadcoco@kpmg.it', 'Jawad', 'Coco'),
  ('mmontemagno@kpmg.it', 'Mirko', 'Montemagno'),
  ('chiarabalestra@kpmg.it', 'Chiara', 'Balestra'),
  ('mspigolon@kpmg.it', 'Michael', 'Spigolon'),
  ('csimonetti@kpmg.it', 'Clara', 'Simonetti'),
  ('asokur@kpmg.it', 'Anastasiia', 'Sokur'),
  ('fpellicano@kpmg.it', 'Federica', 'Pellicanò'),
  ('rconcoreggi@kpmg.it', 'Rosetta', 'Concoreggi'),
  ('andreamelison@kpmg.it', 'Andrea', 'Melison'),
  ('lgabrielli@kpmg.it', 'Luna', 'Gabrielli'),
  ('gcannizzaro@kpmg.it', 'Gabriele', 'Cannizzaro'),
  ('vvisalli@kpmg.it', 'Valeria', 'Visalli'),
  ('rquaglietta@kpmg.it', 'Rita', 'Quaglietta'),
  ('giuliapassarelli@kpmg.it', 'Giulia', 'Passarelli'),
  ('maguzzi@kpmg.it', 'Mariachiara', 'Aguzzi'),
  ('pbarletta@kpmg.it', 'Paolo', 'Barletta'),
  ('mcorritore@kpmg.it', 'Marina', 'Corritore'),
  ('cbazzoni@kpmg.it', 'Carlotta', 'Bazzoni'),
  ('crusconi@kpmg.it', 'Clara', 'Rusconi'),
  ('federicofrigerio@kpmg.it', 'Federico', 'Frigerio'),
  ('avendruscolo@kpmg.it', 'Andrea', 'Vendruscolo'),
  ('estecchezzini@kpmg.it', 'Edoardo', 'Stecchezzini'),
  ('lmiatto@kpmg.it', 'Lisa', 'Miatto'),
  ('karimruffin@kpmg.it', 'Karim', 'Ruffin'),
  ('asandona@kpmg.it', 'Alice', 'Sandonà'),
  ('ccavalli@kpmg.it', 'Carlotta', 'Cavalli'),
  ('btaricco@kpmg.it', 'Beatrice', 'Taricco'),
  ('svanzan@kpmg.it', 'Sarah', 'Vanzan'),
  ('amasiero1@kpmg.it', 'Andrea', 'Masiero'),
  ('annamariadeluca@kpmg.it', 'Anna Maria', 'De Luca'),
  ('cbobbio@kpmg.it', 'Chiara', 'Bobbio'),
  ('sbonazzi@kpmg.it', 'Serena', 'Bonazzi'),
  ('apolga@kpmg.it', 'Andrea', 'Polga'),
  ('gcostaglioli@kpmg.it', 'Gabriele', 'Costaglioli'),
  ('rstara@kpmg.it', 'Rebecca', 'Stara'),
  ('csalvatoni@kpmg.it', 'Costanza', 'Salvatoni'),
  ('abertino@kpmg.it', 'Aurora', 'Bertino'),
  ('gcitelli@kpmg.it', 'Greta', 'Citelli'),
  ('cagressi@kpmg.it', 'Carlotta', 'Agressi'),
  ('atanini@kpmg.it', 'Arianna', 'Tanini'),
  ('alessandrograsso@kpmg.it', 'Alessandro', 'Grasso'),
  ('icattozzo@kpmg.it', 'Ilaria', 'Cattozzo'),
  ('nsenisevolpe@kpmg.it', 'Nathan', 'Senise Volpe'),
  ('fdazzi@kpmg.it', 'Francesca', 'Dazzi'),
  ('apossenti@kpmg.it', 'Agostino', 'Possenti'),
  ('mdugatto@kpmg.it', 'Martina', 'Dugatto'),
  ('mmolfese@kpmg.it', 'Maria', 'Molfese'),
  ('martinasaccoman@kpmg.it', 'Martina', 'Saccoman'),
  ('dzucchini@kpmg.it', 'Davide', 'Zucchini'),
  ('gtozzato@kpmg.it', 'Giacomo', 'Tozzato'),
  ('mincertiboni@kpmg.it', 'Mattia', 'Incerti Boni'),
  ('selifani@kpmg.it', 'Silvia', 'Elifani'),
  ('corradoloreto@kpmg.it', 'Corrado', 'Loreto'),
  ('frestuccia@kpmg.it', 'Francesco', 'Restuccia'),
  ('vgobbato@kpmg.it', 'Valentina', 'Gobbato'),
  ('ibabetto@kpmg.it', 'Irene', 'Babetto'),
  ('nbassani@kpmg.it', 'Nicola', 'Bassani'),
  ('sbiffanti@kpmg.it', 'Serena', 'Biffanti'),
  ('abafaro@kpmg.it', 'Alessandro', 'Bafaro'),
  ('noreste@kpmg.it', 'Noemi', 'Oreste'),
  ('mcolli1@kpmg.it', 'Matteo', 'Colli'),
  ('apresti@kpmg.it', 'Alberto', 'Presti'),
  ('ativeron@kpmg.it', 'Alessandro', 'Tiveron'),
  ('bperosa@kpmg.it', 'Bianca', 'Perosa'),
  ('spalladino@kpmg.it', 'Saverio', 'Palladino'),
  ('sgrezzani@kpmg.it', 'Sofia', 'Grezzani'),
  ('sfenu@kpmg.it', 'Stefano Mario', 'Fenu'),
  ('frizzo1@kpmg.it', 'Francesco Emanuele', 'Rizzo'),
  ('giuliamarchesi@kpmg.it', 'Giulia', 'Marchesi'),
  ('abenetton@kpmg.it', 'Anna', 'Benetton'),
  ('rcillia@kpmg.it', 'Roberta', 'Cillia'),
  ('lsanchioni@kpmg.it', 'Luca', 'Sanchioni'),
  ('cnasti@kpmg.it', 'Claudia', 'Nasti'),
  ('cremigio@kpmg.it', 'Cecilia', 'Remigio'),
  ('amastrototaro@kpmg.it', 'Alessia', 'Mastrototaro'),
  ('francescamonti@kpmg.it', 'Francesca', 'Monti'),
  ('rboscaino@kpmg.it', 'Rossana', 'Boscaino'),
  ('lcasalanguida@kpmg.it', 'Letizia', 'Casalanguida'),
  ('falvisi@kpmg.it', 'Francesco', 'Alvisi'),
  ('giampaolovolpe@kpmg.it', 'Giampaolo', 'Volpe'),
  ('rpalladini@kpmg.it', 'Riccardo', 'Palladini'),
  ('francescatruscello@kpmg.it', 'Francesca', 'Truscello'),
  ('silviaconte@kpmg.it', 'Silvia', 'Conte'),
  ('matteoazanardi@kpmg.it', 'Matteo Alfredo', 'Zanardi'),
  ('mcurelli@kpmg.it', 'Marco', 'Curelli'),
  ('rcervesato@kpmg.it', 'Rossana', 'Cervesato'),
  ('fcovili@kpmg.it', 'Fabio', 'Covili'),
  ('marcogiovagnoni@kpmg.it', 'Marco', 'Giovagnoni'),
  ('leonardoperego@kpmg.it', 'Leonardo', 'Perego'),
  ('sebastianovaccari@kpmg.it', 'Sebastiano Giuliano', 'Vaccari'),
  ('michelezheng@kpmg.it', 'Yujun', 'Zheng'),
  ('giovanniorsi@kpmg.it', 'Giovanni', 'Orsi'),
  ('bfabiano@kpmg.it', 'Benedetta', 'Fabiano'),
  ('wdaponte@kpmg.it', 'William', 'Da Ponte'),
  ('gianfilippoagostini@kpmg.it', 'Gianfilippo', 'Agostini'),
  ('filipporuggeri@kpmg.it', 'Filippo', 'Ruggeri'),
  ('cdepalo@kpmg.it', 'Carlotta', 'De Palo'),
  ('srabolini@kpmg.it', 'Silvia', 'Rabolini'),
  ('dlaudizi@kpmg.it', 'Diego', 'Laudizi'),
  ('lorenzoconsoli@kpmg.it', 'Lorenzo', 'Consoli'),
  ('giuseppelongo@kpmg.it', 'Giuseppe', 'Longo'),
  ('eimbriaco@kpmg.it', 'Elena', 'Imbriaco'),
  ('eprandi@kpmg.it', 'Elisa', 'Prandi'),
  ('cgalassi@kpmg.it', 'Camilla', 'Galassi'),
  ('fcerni@kpmg.it', 'Scipione', 'Cerni'),
  ('ebrosera@kpmg.it', 'Elisa', 'Broserà'),
  ('gcaregnato@kpmg.it', 'Giovanni', 'Caregnato'),
  ('saraferrari@kpmg.it', 'Sara', 'Ferrari'),
  ('ecaliano@kpmg.it', 'Emanuela', 'Caliano'),
  ('vpiersantini@kpmg.it', 'Valentina', 'Piersantini'),
  ('acamarda@kpmg.it', 'Alba', 'Camarda'),
  ('alessiacavaliere@kpmg.it', 'Alessia', 'Cavaliere'),
  ('arenacco@kpmg.it', 'Alessandro', 'Renacco'),
  ('srizzi@kpmg.it', 'Sofia', 'Rizzi')
on conflict (email) do update set nome = excluded.nome, cognome = excluded.cognome;
